### PR TITLE
Updated ESX

### PR DESCRIPTION
**Pull request by BronxDre**
I updated the ESX version to match the changes made to the VRP version. Tested and everything seems to work fine, no errors show up.

### CODE REVIEW

**Comment by BronxDre** [comment]
Need to work something. Will pull again when done

**Review by Mikou27 — COMMENTED** [review]
Hi,thank you for the work, bring back the french translation please and credit yourself : ).

**Review by Mikou27 — APPROVED** [review]
thank you!

**Review by Mikou27 — APPROVED** [review]
thank you!

**Pull request merged**
